{% set name = "pygeohash" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ca41a991d3a2fe4d6ca51d8ceea31581749bf3ceb4cb0d3d6bff3ed32f9e5cd4

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pygeohash

about:
  home: https://github.com/wdm0006/pygeohash
  license: AGPL-3.0
  license_family: AGPL
  license_file: LICENSE.txt
  summary: 'A module for decoding and encoding geohashes to and from latitude and longitude coordinates'

  description: |
    Pygeohash is a Python module that provides functions for
    decoding and encoding geohashes to and from latitude and
    longitude coordinates, and doing basic calculations and
    approximations with them.


extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - adbeda
    - agcopenhaver
    - oblute
